version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-vanity-converter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1oky961k4xvhg"
s3_prefix = "aws-vanity-converter"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
