AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-vanity-converter

  A lambda function / dynamoDB interface for converting phone numbers to vanity numbers.
  
Resources:
  NumberToVanityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: convert-number/
      Handler: app.convertNumberHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64

  CustomerVanityNumberTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: phoneNumber
        Type: String
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      # SSESpecification:
      #   SSEEnabled: false
      TableName: VanityNumbers

Outputs:
  NumberToVanityFunction:
    Description: "NumberToVanity Lambda Function ARN"
    Value: !GetAtt NumberToVanityFunction.Arn
  NumberToVanityFunctionIamRole:
    Description: "Implicit IAM Role created for NumberToVanity function"
    Value: !GetAtt NumberToVanityFunction.Arn
